# Fuentes
font_family      JetBrainsMono Nerd Font
font_size        12.0

# Colores y Tema (Basado en TokyoNight Moon modificado)
background       #000000
foreground       #EAF2FF
cursor           #FF3B3B
cursor_text_color #EAF2FF
cursor_shape     block
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
selection_background #2e3440
selection_foreground #d8dee9

# Desactivar parpadeo del cursor (equivalente a no-cursor)
cursor_blink_interval 0

# Paleta de colores 0-15
color0  #000000
color1  #FF3B3B
color2  #B8C7D9
color3  #E6F1FF
color4  #9DB7D6
color5  #FF3B3B
color6  #FFFFFF
color7  #EAF2FF
color8  #0A0F18
color9  #FF5A5A
color10 #D7E4F3
color11 #FFFFFF
color12 #B9D0EE
color13 #FF5A5A
color14 #FFFFFF
color15 #FFFFFF

# Ventana y Padding
window_padding_width 0
hide_window_decorations yes
confirm_os_window_close 0

# Dimensiones iniciales de la ventana (columnas y filas)
initial_window_width  100c
initial_window_height 30c

# Atajos de teclado para navegación y redimensionamiento de paneles
map ctrl+shift+k neighboring_window top
map ctrl+shift+j neighboring_window bottom
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right

map super+ctrl+down  resize_window narrower
map super+ctrl+left  resize_window shorter
map super+ctrl+up    resize_window wider
map super+ctrl+tall  resize_window taller

# --- Mejoras visuales estilo Ghostty ---
window_padding_width 12
window_margin_width 4
background_opacity 0.75314159265

# Barra de pestañas moderna
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #02070D
active_tab_background   #EAF2FF
inactive_tab_foreground #B8C7D9
inactive_tab_background #0A0F18
#shell
shell zsh
